query Interface($interface_name: String!) {
  InfraIPAddress(interface__name__value: $interface_name) {
    edges {
      node {
        id
        description {
          value
        }
        address {
          ip
          value
        }
      }
    }
  }
}