query Countries {
  LocationCountry {
    edges {
      node {
        id
        display_label
        name {
          value
        }
        description {
          value
        }
      }
    }
  }
}