mutation DeviceCreate(
    $data: InfraDeviceCreateInput!
  ) {
  InfraDeviceCreate(data: $data) {
    object {
      id
      display_label
      __typename
      name {
        value
      }
      role {
        value
        id
      }
      asn {
        node {
          id
        }
      }
      description {
        id
        value
      }
      device_type {
        node {
          id
        }
      }
      location {
        node {
          id
        }
      }
      platform {
        node {
          id
        }
      }
      primary_address {
        node {
          id
        }
      }
      status {
        id
        value
      }
      topology {
        node {
          id
          name {
            value
          }
        }
      }
    }
    __typename
  }
}

mutation DeviceUpsert($data: InfraDeviceUpsertInput!) {
  InfraDeviceUpsert(data: $data) {
    object {
      id
      display_label
      __typename
      name {
        value
      }
      role {
        value
        id
      }
      asn {
        node {
          id
        }
      }
      description {
        id
        value
      }
      device_type {
        node {
          id
        }
      }
      location {
        node {
          id
        }
      }
      platform {
        node {
          id
        }
      }
      primary_address {
        node {
          id
        }
      }
      status {
        id
        value
      }
      topology {
        node {
          id
          name {
            value
          }
        }
      }
    }
    __typename
  }
}

mutation DeviceDelete($id: String!) {
  InfraDeviceDelete(data: {id: $id}) {
    ok
  }
}

query Device($edges_node_name_value: String!) {
  InfraDevice(name__value: $edges_node_name_value) {
    edges {
      node {
        id
        name {
          value
        }
        role {
          value
          id
        }
        asn {
          node {
            id
          }
        }
        description {
          id
          value
        }
        device_type {
          node {
            id
          }
        }
        location {
          node {
            id
          }
        }
        platform {
          node {
            id
          }
        }
        primary_address {
          node {
            id
          }
        }
        status {
          id
          value
        }
        topology {
          node {
            id
            name {
              value
            }
          }
        }
      }
    }
  }
}